### ISSUE TITLE
The extension does not work

### ISSUE THREAD

**Issue by bkmeneguello** [filipeisho/pronounce#1]
I've installed the extension in Firefox 83.0 (64-bit) in Arch Linux, it shows the square icon in toolbar, when I click on it a popup with a single checkbox and an empty combo box appears. Nothing else happens.

**Comment by tryhardfifi** [comment]
Sorry to hear! The data inside the combo box comes from SpeechSynthesis API. I think Firefox on Arch Linux is not currently supporting the TTS feature from SpeechSynthesis API... 

I found [this](https://bbs.archlinux.org/viewtopic.php?pid=1656562#p1656562) old thread of people having the same issue, they are looking for another TTS engine because the SpeechSynthesis API wasn't working. This thread is old and I haven't found any update on the status of this.

**Comment by bkmeneguello** [comment]
Yeah, I tried in Windows and worked well. Seems FF and Chromium builds in most Linux distros are not linked to the TTS engines.
